server:
  port: 8080
  servlet:
    context-path: /shopapp

spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/project_1"
    username: root
    password: tuancuong@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # VNPay Configuration
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

logging:
  level:
    org.springframework.security: DEBUG